services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: kflix-web
    ports:
      - "8181:80"
    environment:
      - APP_NAME=KFLIX
      - APP_ENV=production
      - APP_KEY=base64:e9446fc20b1ede0433ee461263a41c9b0046bd30e75e263e5dcc6fcace68025e
      - APP_DEBUG=false
      - APP_URL=http://localhost:8181
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=kflix_db
      - DB_USERNAME=kflix_user
      - DB_PASSWORD=kflix_password
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: kflix-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kflix_db
      MYSQL_USER: kflix_user
      MYSQL_PASSWORD: kflix_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:
